### ISSUE TITLE
Milestone 2 checklist

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/eda_utils_py#19]
**1. Write test cases and code iteratively**
 
- [x] Exception handling 
    - The function should be written defensively. That is, it should handle incorrect input and errors detected during execution via throwing exceptions with useful error messages, and there should be tests to confirm that the exceptions result in the expected behaviour of the function.
- [x] Planning and organizing your work
    - Any ideas/notes that you generate that are related to your assigned function should be recorded in the corresponding issue you created in milestone 1. The issue should be closed by the end of milestone 2.
    - If you think of new ideas or test cases and you do not have time to implement them in this milestone, create an issue for them which you can complete during the next milestone.

**2. R package checklist**

- [x] Create project structure for the R project 
- [x]  R package function specifications
