### ISSUE TITLE
Python package checklist

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/eda_utils_py#30]
- [x] [1. GitHub actions workflow for continuous integration](https://github.com/UBC-MDS/eda_utils_py/issues/31)
    Your task here is to make sure the workflow in .github/workflows/build.yml is correctly configured so that at a minimum, it runs the test suite and style checkers on pushes and pull requests to your project's repository's deployment branch (typically the main branch).

- [x] [2. GitHub actions workflow for continuous deployment](https://github.com/UBC-MDS/eda_utils_py/issues/32)
    Your task here is to make sure the workflow in .github/workflows/deploy.yml is correctly configured so it runs the test suite, style checkers and deplys to package to test PyPI on pushes to your project's repository's deployment branch (typically the main branch)

- [x] [3. Documentation](https://github.com/UBC-MDS/eda_utils_py/issues/33)
    Your package documentation should be very clear by the end of this milestone and deployed by ReadTheDocs. All docstrings for all functions should be rendered using the napolean Sphinx extnesion and readable on ReadTheDocs. Your documentation should also include a demonstration of how to use each function in the package, so that any user with minimal Python expertise would be able to run your package functions and play around with them.
