### ISSUE TITLE
Milestone 1 checklist

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/eda_utils_py#4]
- [x] 1. [Team work contract](https://github.com/UBC-MDS/dsci524-group18/issues/2)
- [x] 2. [Pick a topic](https://github.com/UBC-MDS/dsci524-group18/issues/1)
- [x] 3. Create project structure for the Python project
- [x] 4. [Function specifications](https://github.com/UBC-MDS/dsci524-group18/issues/3)
- [x] 5. [Manage issues](https://github.com/UBC-MDS/dsci524-group18/projects)

Deliverables:

- [x] 1. The URL of your public project’s repo
- [x] 2. The URL to a release on your project repo named v0.1.0
- [x] 3. A link to your team work document that is accessible to the teaching team. Alternatively a copy of your team work document can be pasted there.
